apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: prov-app-dev
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: ${STORAGE_CLASS_NAME}
      volume.beta.kubernetes.io/storage-provisioner: ${STORAGE_PROVISIONER}
    creationTimestamp: null
    labels:
      app: prov-app
    name: prov-history
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Mi
parameters:	
- name: STORAGE_PROVISIONER
  required: true
- name: STORAGE_CLASS_NAME
  required: true