apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: prov-app-test
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: ${STORAGE_CLASS_DATA}
      volume.beta.kubernetes.io/storage-provisioner: ${STORAGE_PROVISIONER}
    creationTimestamp: null
    labels:
      app: prov-app
    name: prov-history
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Mi
parameters:	
- name: STORAGE_PROVISIONER
- name: STORAGE_CLASS_DATA
- name: STORAGE_CLASS_BACKUP
